const mongoose = require("mongoose");

const OrdersSchema = new mongoose.Schema({
  user: mongoose.Mixed,
  createdBy: mongoose.Mixed,
  items: [mongoose.Mixed],
  payment: [mongoose.Mixed],
  totalAmount: { type: mongoose.Mixed },
  address: { type: mongoose.Mixed },
  company: { type: mongoose.Mixed },
  email: { type: mongoose.Mixed },
  phone: { type: mongoose.Mixed },
  displayName: { type: mongoose.Mixed },
  dueAmount: { type: mongoose.Mixed },
  data: { type: mongoose.Mixed },
  download: { type: mongoose.Mixed },
  invoiceId: { type: String },
  autoGenerated: { type: Boolean },
  notes: { type: String },
  date: {
    type: Date,
    default: Date.now,
  },
  status: {
    type: String,
    default: "generated",
  },
  title: {
    type: String,
    default: "Paid for Order at Psymate",
  },
  type: { type: String, default: "order" },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  updatedAt: {
    type: Date,
    default: Date.now,
  },
});

const Orders = mongoose.model("Orders", OrdersSchema);

module.exports = { Orders };
